#taken from: https://github.com/marketplace/actions/ftp-deploy
name: 🚀 Deploy website on push

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        dry-run: ${{ secrets.dry_run }}
        log-level: standard
        port: 21
        local-dir: ./
        server-dir: ./
        protocol: ftps
        security: strict
        exclude: .git*
          - **.git*
          - .git*/**
          -  **/.git*/**
          - archiv/**
